### ISSUE TITLE
报个错

### ISSUE THREAD

**Issue by qchenac** [junyiz/dature#4]
给老哥请个安先 LL

然后是报错，抓取完毕之后显示下面这个，而且博文图片有漏抓，不知跟这个错有关西不
抓取完毕, 博客存储目录：/Users/qulo/blog

/usr/local/lib/node_modules/dature/node_modules/picture-downloader/pictureDownloader.js:26
  const request = url.startsWith('https') ? https.request : http.request
                      ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at pictureDownloader (/usr/local/lib/node_modules/dature/node_modules/picture-downloader/pictureDownloader.js:26:23)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/dature/node_modules/picture-downloader/pictureDownloader.js:41:33)
    at ClientRequest.emit (node:events:394:28)
    at Socket.socketCloseListener (node:_http_client:423:9)
    at Socket.emit (node:events:406:35)
    at TCP.<anonymous> (node:

**Comment by junyiz** [comment]
抓取哪个博客出现的呢？

**Comment by qchenac** [comment]
dature -t sina -u 1310876224
抱歉回晚了 老哥 之前出差 不记得是哪个博客了 回来用老电脑才在terminal里翻出来

**Comment by junyiz** [comment]
试了一下，不报错

**Comment by qchenac** [comment]
显示是可以抓取，但抓取完毕下面会显示以下内容，然后发现有些图片会漏抓，不知道咋回事
/usr/local/lib/node_modules/dature/node_modules/picture-downloader/pictureDownloader.js:26
  const request = url.startsWith('https') ? https.request : http.request
                      ^

TypeError: Cannot read properties of undefined (reading 'startsWith')
    at pictureDownloader (/usr/local/lib/node_modules/dature/node_modules/picture-downloader/pictureDownloader.js:26:23)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/dature/node_modules/picture-downloader/pictureDownloader.js:41:33)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketCloseListener (node:_http_client:423:9)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12)

Node.js v17.2.0

**Comment by junyiz** [comment]
已修复了
