### ISSUE TITLE
由于博客已经被封，仅自己可见，外人无法访问，如何处理

### ISSUE THREAD

**Issue by lixin4306ren** [junyiz/dature#5]
有输入密码的参数吗？

**Comment by chopper-go** [comment]
博客凉了，新浪也不事先通知一下

**Comment by junyiz** [comment]
> 有输入密码的参数吗？

抓取的时候，带上登录态，应该就可以了，不过这需要开发

**Comment by mxxba** [comment]
> 

我抓取的时候是登录状态，但是现实抓取0文章。请大佬抽空解决一下吧？

**Comment by junyiz** [comment]
已支持带 cookie 抓取，cookie 设置方式如下：

dature -u 1263917762 -c 'xxxxxx'

注意 xxxxxx 为 cookie

**Comment by lixin4306ren** [comment]
试了下好像不行，是因为cookie里有乱码吗？May 03 2022 17:43:11 GMT+0800，这种时间后面的括号里有乱码

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/14223132/166434367-2af07c76-1e7f-40a4-aa22-9b36960e8980.png">

**Comment by junyiz** [comment]
> 

cookie 里的乱码已经处理了，这次是 cookie 里的中文导致的，也已经处理了，你再下载新代码试试

**Comment by lixin4306ren** [comment]
已成功，多谢。

**Comment by lixin4306ren** [comment]
不好意思，抓取到中间有报错中断了，是因为有的图片是外链的，外链已消失，如何处理？

```
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:371:5)
    at onParseError (node:internal/url:552:9)
    at new URL (node:internal/url:628:5)
    at new ClientRequest (node:_http_client:111:30)
    at request (node:http:96:10)
    at pictureDownloader (/usr/local/lib/node_modules/dature/lib/picture-downloader.js:30:15)
    at /usr/local/lib/node_modules/dature/lib/sina.js:63:15
    at String.replace (<anonymous>)
    at extract (/usr/local/lib/node_modules/dature/lib/sina.js:57:10)
    at runMicrotasks (<anonymous>) {
  input: 'http&#58;//image215.poco.cn/mypoco/myphoto/20091123/22/43485264200911232212361504696171586_072_640.jpg',
  code: 'ERR_INVALID_URL'
}
```

**Comment by junyiz** [comment]
已处理了，你再下载最新代码

**Comment by lixin4306ren** [comment]
搞定了，非常感谢，已赞助支持。
